선형회귀 
==
다루는 내용
--
- 선형회귀 개념
- 머신러닝 개념
- 경사하강법

In [1]:
import  numpy as np

독립변수 x 생성
--

In [2]:
x = np.random.uniform(low=0.0, high=1.0, size=100)
print(x.shape)
x[:5]

(100,)


array([0.35627615, 0.33264117, 0.63983014, 0.64855983, 0.99758731])

종속변수 y = wx + b 생성
--

In [3]:
# w=10 , b=2
y = 10* x + 2
print (y.shape)
y[0:5]

(100,)


array([ 5.56276151,  5.32641172,  8.39830137,  8.48559834, 11.97587307])

가중치 w와 절편 b 학습
--

 경사하강법
--

In [4]:
num_epoch = 300

# 초기값은 랜덤하게 지정
w = np.random.uniform(low=0.0, high=1.0)
b = np.random.uniform(low=0.0, high=1.0)

for epoch in range(num_epoch):
    y_pred = w*x + b
    error = np.abs(y_pred - y).mean()
    if error < 0.05:
        break
    w = w - ((y_pred - y)*x).mean()
    b = b - (y_pred - y).mean()
    print(f"{epoch:2}  w = {w:.4f} ,  b = {b:.4f} , error = {error:.4f}")

print("---" * 10)
print(f"{epoch:2}  w = {w:.4f} ,  b = {b:.4f} , error = {error:.4f}")


 0  w = 4.8243 ,  b = 6.9211 , error = 6.7079
 1  w = 4.1831 ,  b = 4.6574 , error = 2.2781
 2  w = 4.9378 ,  b = 4.9866 , error = 1.6797
 3  w = 5.2485 ,  b = 4.5991 , error = 1.4343
 4  w = 5.6449 ,  b = 4.4396 , error = 1.3439
 5  w = 5.9789 ,  b = 4.2360 , error = 1.2306
 6  w = 6.2957 ,  b = 4.0646 , error = 1.1366
 7  w = 6.5851 ,  b = 3.9019 , error = 1.0470
 8  w = 6.8526 ,  b = 3.7533 , error = 0.9652
 9  w = 7.0989 ,  b = 3.6160 , error = 0.8896
10  w = 7.3261 ,  b = 3.4895 , error = 0.8200
11  w = 7.5354 ,  b = 3.3729 , error = 0.7558
12  w = 7.7283 ,  b = 3.2654 , error = 0.6966
13  w = 7.9062 ,  b = 3.1663 , error = 0.6421
14  w = 8.0701 ,  b = 3.0750 , error = 0.5918
15  w = 8.2212 ,  b = 2.9909 , error = 0.5455
16  w = 8.3604 ,  b = 2.9133 , error = 0.5028
17  w = 8.4888 ,  b = 2.8418 , error = 0.4634
18  w = 8.6071 ,  b = 2.7759 , error = 0.4271
19  w = 8.7161 ,  b = 2.7152 , error = 0.3937
20  w = 8.8166 ,  b = 2.6592 , error = 0.3629
21  w = 8.9093 ,  b = 2.6076 , err

변수가 2개인 경우
--

In [5]:
x1 = np.random.uniform(low=0.0, high=1.0, size=100)
x2 = np.random.uniform(low=0.0, high=1.0, size=100)

y = 3 * x1 + 5* x2 + 2

print(y.shape)
y[:5]

(100,)


array([3.51595155, 6.08940523, 6.96655101, 6.92788011, 3.73138544])

학습속도를 반영
--

In [6]:
num_epoch = 100
learning_rate = 1.2

w1 = np.random.uniform(low=0.0, high=1.0)
w2 = np.random.uniform(low=0.0, high=1.0)
b = np.random.uniform(low=0.0, high=1.0)

for epoch in range(num_epoch):
    y_pred = w1*x1 + w2*x2 + b
    error = np.abs(y_pred - y).mean()
    if error < 0.01:
        break
    w1 = w1 - learning_rate*((y_pred - y)* x1).mean()
    w2 = w2 - learning_rate*((y_pred - y)* x2).mean()
    b = b -learning_rate* ((y_pred - y)).mean()

    print(f"{epoch:2} w1 = {w1:.6f},  w2 = {w2:.6f}, b = {b:.6f} , error = {error:.6f}")

print("---" * 10)
print(f"{epoch:2} w1 = {w1:.4f},  w2 = {w2:.4f}, b = {b:.4f}, error = {error:.4f}")

 0 w1 = 3.590841,  w2 = 3.951610, b = 5.790465 , error = 4.481176
 1 w1 = 1.603157,  w2 = 2.000276, b = 1.527616 , error = 3.552374
 2 w1 = 3.141260,  w2 = 3.785504, b = 4.589637 , error = 2.551685
 3 w1 = 2.006700,  w2 = 2.711518, b = 2.108217 , error = 2.067851
 4 w1 = 2.900283,  w2 = 3.783085, b = 3.842596 , error = 1.445568
 5 w1 = 2.256232,  w2 = 3.206236, b = 2.389970 , error = 1.210521
 6 w1 = 2.778706,  w2 = 3.860325, b = 3.364327 , error = 0.836642
 7 w1 = 2.416419,  w2 = 3.563100, b = 2.506985 , error = 0.714452
 8 w1 = 2.724950,  w2 = 3.971196, b = 3.047340 , error = 0.518275
 9 w1 = 2.524255,  w2 = 3.829478, b = 2.535424 , error = 0.445023
10 w1 = 2.709185,  w2 = 4.091158, b = 2.828885 , error = 0.357242
11 w1 = 2.600899,  w2 = 4.034394, b = 2.518253 , error = 0.316236
12 w1 = 2.714165,  w2 = 4.207712, b = 2.672074 , error = 0.275590
13 w1 = 2.658468,  w2 = 4.196025, b = 2.479452 , error = 0.244406
14 w1 = 2.729936,  w2 = 4.315028, b = 2.555006 , error = 0.222132
15 w1 = 2.

라이브러리를 이용
--

In [7]:
import pandas as pd
from sklearn.linear_model import LinearRegression

X = pd.DataFrame(x1)
X[1]= x2

In [8]:
leg = LinearRegression().fit(X, y)
print(leg.coef_)
print(leg.intercept_)

[3. 5.]
2.0
